version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    networks:
      - sharq_network
    env_file:
      - .env
networks:
  sharq_network:
    external: true