"""add relationship for study_info

Revision ID: a4c8f7ca4fae
Revises: 31fae9496539
Create Date: 2025-07-01 13:43:28.953890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c8f7ca4fae'
down_revision: Union[str, Sequence[str], None] = '31fae9496539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passport_series_number', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=100), nullable=False),
    sa.Column('authority_code', sa.String(length=10), nullable=False),
    sa.Column('place_of_birth', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_language', sa.String(), nullable=False),
    sa.Column('study_form', sa.String(), nullable=False),
    sa.Column('study_direction', sa.String(), nullable=False),
    sa.Column('exam_form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_info')
    op.drop_table('passport_data')
    # ### end Alembic commands ###
